GET http://localhost:5000/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3M2Q5NjdhMjU0MWM5MTQ3ZjE2YmE1YiIsInJvbGUiOlsidXNlciJdLCJpYXQiOjE3MzIwOTE1MTYsImV4cCI6MTczMjE3NzkxNn0.hgrPBOYNvM1DN4PcoXHujXxCLb6KYuZSD_yOeuGO_DU

